import React from 'react';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import CustomNavbar from '../components/CustomNavbar';


const inter = Inter({ subsets: ['latin'] });

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
   
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body className={inter.className}>
      
      <CustomNavbar/>
      
      <div className="container">
        {children}
        </div>
      </body>
    </>
     
  );
};

export default RootLayout;
